'use strict'
// require('./compiler-test.js')
require('./parser-test.js')
require('./extend-test.js')
require('./partials-test.js')
require('./compilers/string-test.js')
require('./compilers/text-test.js')
require('./compilers/element-test.js')
require('./compilers/attribute-test.js')
require('./compilers/event-test.js')
require('./nut-test.js')
require('./compilers/tag-test.js')
// require('./api-factories-test.js')
// require('./compilers/children-test.js')
// require('./compilers/requirements-test.js')
