'use strict'
import './parser-test.js'
import './extend-test.js'
import './partials-test.js'
import './api-factories-test.js'
// import './compiler-test.js'
import './compilers/string-compiler-test.js'
import './compilers/attribute-compiler-test.js'
