'use strict'
import './parser-test.js'
import './extend-test.js'
import './partials-test.js'
import './api-factories-test.js'
// import './compiler-test.js'
import './compilers/attribute-test.js'
import './compilers/string-test.js'
import './compilers/attribute-test.js'
import './compilers/element-test.js'
import './compilers/event-test.js'
import './compilers/tag-test.js'
// import './compilers/children-test.js'
import './nut-test.js'
