ui: mocha-bdd
browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  - name: ie
    version: [10..latest]
  - name: iphone
    version: 6.1
  - name: android
    version: 4.4